version: '3.7'

services:
  web: &appbase
    build:
      context: .
      target: "base"
    command: >
      bash -c "python manage.py migrate 
      && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - .:/app

  test:
    <<: *appbase
    command: make para-test
