# Generated by Django 4.1.2 on 2022-10-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('file', models.FileField(upload_to='files')),
                ('description', models.CharField(blank=True, max_length=32, null=True)),
                ('author', models.CharField(blank=True, max_length=32, null=True)),
                ('genre', models.CharField(choices=[('COM', 'Comedy'), ('HOR', 'Horror'), ('OTH', 'Other')], default='OTH', max_length=3)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('language', models.CharField(blank=True, max_length=32)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('contents', models.ManyToManyField(blank=True, to='base.content')),
                ('subchannels', models.ManyToManyField(blank=True, to='base.channel')),
            ],
        ),
    ]
