# Generated by Django 4.1.2 on 2022-11-01 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_content_file_contentfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
